FROM golang:1.24-alpine AS build
WORKDIR /app
COPY messaging/go.mod messaging/main.go ./
RUN go mod tidy
RUN go build -o messaging main.go

FROM alpine
WORKDIR /app
COPY --from=build /app/messaging .
EXPOSE 8082
CMD ["./messaging"]
