FROM golang:1.24-alpine AS build
WORKDIR /app
# Copy entire messaging module
COPY messaging/ ./messaging
WORKDIR /app/messaging
# Ensure dependencies and go.sum entries
RUN go mod tidy
# Build binary to root
RUN go build -o /messaging .

FROM alpine
WORKDIR /app
COPY --from=build /messaging .
EXPOSE 8082
CMD ["./messaging"]
