FROM golang:1.24-alpine AS build
WORKDIR /app
COPY identity/go.mod identity/main.go ./
RUN go mod tidy
RUN go build -o identity main.go

FROM alpine
WORKDIR /app
COPY --from=build /app/identity .
EXPOSE 8081
CMD ["./identity"]
